- psake.psm1
The version paths have not changed between .NET 4.5.2 and 4.5.1. 
This change effectively treats 4.5.2 as 4.5.1.
> Add support for 4.5.2

- psake.psm1
- specs/dotNet4.6_should_pass.ps1
On a clean install of VS2015, there's no MsBuild version 12.
> Added support for .net 4.6

- examples/paralleltasks.ps1
just added an example script that shows how someone might do parallel tasks without too much headache. this doesn't deal with exceptions just yet but i think it's a great start. i can easily see something like this making it's way into the `Invoke-Task` using some `parallelDepends` argument/parameter. This can also be simply modified to point to a different script for the subsequent `Invoke-psake` calls.
> Adding an example for a parallel task

- docs/structure-of-a-psake-build-script.md
I was reading about psake and one of the pages had bad formatting and made it very hard to figure out what was going on. The following was done:
* Fixed format of function table
* Added PowerShell syntax highlighting to code sample.
* Used a code block instead of the _pre._ (which didn't work) for the BNF.
> Greg Mcguffey patch: fix table formatting in documents

- docs/team-city.md
updated the TeamCity markdown file to show how to get all of the defined TeamCity build parameters into a single hash.
> updates TeamCity documentation regarding build parameters

- README.markdown
- docs/dot-net-solution.md
- docs/getting-help.md
- docs/how-to-fail-a-build.md
- psake.psm1
- specs/using_initialization_block_should_pass.ps1
- tabexpansion/Readme.PsakeTab.txt
- PowerShell
- Internet
- Google
- FAQ
- command
- overridden
- override
- isn't
> Spelling fixes in docs and script comments

- psake-buildTester.ps1
- psake.psm1
- specs/Get-PSakeScriptTasks_should_pass.ps1
- tabexpansion/PsakeTabExpansion.ps1
This should solve #197. The solution I came up with in the end was to simply check for the presence and value of `$IsWindows`:
```
if (!(Get-Variable -Name IsWindows -ErrorAction SilentlyContinue) -and !$IsWindows)
```
This variable should be present in PS Core and set to $True on windows. So if that variable is not present or if it is true we detect frameworks. If not this part is simply ignored.
The rest of the changes are only aliases that I had to replace with their full cmdlet names because they do not exist under MacOSX or Linux.
> Solve some portability issues with PS Core 6.x on MacOSX

- psake.psm1
Two minor changes.
If the build script defines a custom `FormatTaskName` then also use that to format the header for the *Build Time Report* shown at the end of the build. This improves the consistency of the build log for users who define a custom task header.
Show task timing to millisecond accuracy in the *Build Time Report* instead of to tenths of microseconds.
> Improve Build Time Report

- .gitignore
- .travis.yml
- appveyor.yml
- build.ps1
- build/dotnet-install.ps1
- build/travis.ps1
- tests/Help.tests.ps1
- tests/Manifest.tests.ps1
- tests/Meta.Tests.ps1
- tests/MetaFixers.psm1
- tests/integration/spec.tests.ps1
This PR gets AppVeyor and Travis CI builds working and correctly passing success/failed status.
This also uses Pester to test the spec files and includes a handful of other Pester tests to check the quality of Get-Help against the public functions, the module manifest, spaces vs tabs, etc.
https://ci.appveyor.com/project/psake/psake/build/4.6.0.103
https://travis-ci.org/psake/psake/jobs/298409461
https://travis-ci.org/psake/psake/jobs/298409462
#172 
Get AppVeyor and Travis executing tests correctly.
Modified `appveyor.yml` and `.travis.yml` to execute a common `build.ps1` script. This build script will handle installing dotnet and kicking off the Pester tests.
> Add initial set of Pester tests and execute in AppVeyor/Travis

- psake.psm1
- specs/postAction_runs_on_failed_should_fail.ps1
- specs/taskTearDown_runs_on_failed_test_should_fail.ps1
Replacement for old PR #74. This change ensures that if `postAction` or `taskTearDown` tasks are defined, they will always be called.
From @stephan-dowding in #74:
> A quick patch to fix a little bug bear of mine...
I normally expect things like PostAction and TearDown to be called even if the main Action has failed. This is because it is natural for me to use things like PreAction and SetUp to reserve resources and setup the environment for the Action. I will then use PostAction and TearDown to release those resources and wind down the environment. Having all that stuff hanging around after a test failure was extremely annoying!
I know I could have used try...finally within my Action blocks, but these constructs felt like the natural and intended place for them, hence the pull request! …
> Ensure postAction and taskTeardown tasks get called after action failure

- psake.psm1
New pull request as replace for: #135 
@alexandear @gep13 I like the suggestion of @rvdginste. It's a good idea to move the Pop-Location statement to a finally block. With my solution, the user could end up in a wrong directory, if some script/exe fails. 
Sadly, I’ve removed my fork of psake and can therefore not modify my commit.
That’s the reason why I’ve created a new pull request for the working directory feature.
> Add working directory option to Exec function

- CHANGELOG.md
- src/psake.psd1
- src/public/Invoke-psake.ps1
Bump module version to `v4.7.0` and update changelog to reflect the highlights since the last release.
#225 
#217 
#197 
Release a version of PSake that works on macOS/Linux.
AppVeyor / Travis
> Bump version to v4.7.0 and release

- .vscode/settings.json
My bad.  Steered us wrong on this setting.  This new way will allow you to see the folders in the Explorer view but search will not find text in these folders - by default.
Manually from within VSCode.
> Put in release folders in search.exclude instead of files.exclude

- .travis.yml
Defined a Travis CI matrix in the .travis.yml config file to remove the xcode tag from future Ubuntu Trusty jobs.
Added a Travis CI job matrix to improve definition between macOS and Ubunty Trusty jobs as I learned in my own project: https://github.com/tlindsay42/ArmorPowerShell/blob/master/.travis.yml
#231 
Removes the xcode tag for Ubuntu Trusty Travis CI jobs.
Figured this out last month in my Armor PowerShell Module project.  Example: https://travis-ci.org/tlindsay42/ArmorPowerShell/builds/305173326
> Add Travis CI matrix for improved job tagging

- .travis.yml
- specs/detailedDocs_should_pass.ps1
- specs/docs_should_pass.ps1
- specs/prefer_default_buildfile_over_legacy_should_pass.ps1
- specs/use_default_buildfile_should_pass.ps1
- specs/use_legacy_default_buildfile_should_pass.ps1
- src/private/CleanupEnvironment.ps1
- src/private/ConfigureBuildEnvironment.ps1
- src/private/ExecuteInBuildFileScope.ps1
- src/private/LoadConfiguration.ps1
- src/private/LoadModules.ps1
- src/private/ResolveError.ps1
- src/private/WriteColoredOutput.ps1
- src/private/WriteDocumentation.ps1
- src/public/Exec.ps1
- src/public/Get-PSakeScriptTasks.ps1
- src/public/Invoke-Task.ps1
- src/public/Invoke-psake.ps1
- src/public/Task.ps1
Fix PS ScriptAnalyzer warnings. There should be zero warnings now.
Also normalized casing on $env:path to $env:PATH because on *nix systems env var is upper case.
Broken window theory - if we have too many PSSA warnings they will just be ignored.  By getting to zero it becomes more obvious when new warnings are introduced.
Ran all the Pester tests.
> Fix most PSSA warnings - suppressed a few.

- src/psake.psm1
- src/public/Invoke-psake.ps1
Fixes #239 where seeing "build succeeded" when in fact psake wasn't build anything.  psake executes tasks which may perform a build or may run tests or may do any number of things which are not builds.
Changes the build_success message from `Build succeeded` to `psake succeeded executing <build-file-path>`
#239 
The current message in the context of a larger log file is misleading and isn't easy to "pin to" psake.  I might have an overall build process that uses many different tools to build.  Seeing "Build succeeded" isn't specific enough.  I want to know that output came from psake.
Manually testing by running `Invoke-psake specs\calling_invoke-task_should_pass.ps1`.
> Update build success msg to be more general: psake succeeded

- tabexpansion/PsakeTabExpansion.ps1
Remove cmdlet aliases.
PSScriptAnalyzer warning ['PSAvoidUsingCmdletAliases'](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/AvoidUsingCmdletAliases.md).
> Remove Cmdlet aliases

- README.md
Add another step to the install instructions in the readme for VS2017 builds.
Proposing a documentation updated.
I'd actually prefer that we internalize the VSSetup dependency within psake itself to avoid taking an additional installation dependency.  But that which I do not have time to fix, I must document.
I have installed VSSetup.
> Document dependence on VSSetup module

- src/private/LoadConfiguration.ps1
- src/psake.psm1
The default psake-config.ps1 path was incorrect and probably broke with #228. This prevented the default config file from being loaded when a psake-config.ps1 file was not present in the current build script directory.
#246 
The default `psake-config.ps1` file should be loaded if not present in the current build script directory.
Made changes to default `psake-config.ps1` file in module folder and validated those changes where executed. Also created `psake-config.ps1` file in same directory as build script and validated those changes take precedence over the default config file.
N/A
> Fix #246. Load psake-config.ps1 from correct path in module folder.

- src/private/ConfigureBuildEnvironment.ps1
Current implementation required VSSetup module to be installed in location where PowerShell can find it automatically. Now, before trying to import VSSetup, psake will check if it's not already loaded. This allows to work with VSSetup committed to repository, loading it either by psake-config.ps1 or manually in helper script.
Somewhat fixes #241, because now you don't have to install and maintain additional modules on build servers.
It's not always feasible to install additional modules on build server.
I did not have VSSetup module installed. I have copied VSSetup module to a folder in repository. Then I modified psake-config.ps1 to include VSSetup.psd1 in $config.modules. After this psake used MSBuild 15 and build succeeded, whereas before the change it used version 14.
> Allow working with preloaded VSSetup module

- specs/dotNet4.7.2_should_pass.ps1
- src/private/ConfigureBuildEnvironment.ps1
Added .net 4.7.2 to ConfigureBuildEnvironment.ps1, with only build tools 15.0
this follows the same patter already implemented for .net 4.7 and .net 4.7.2
#256
ci/cd tests are passing
> Adding support for .net 4.7.2

- src/psake.psm1
- src/public/Invoke-psake.ps1
- tests/integration/spec.tests.ps1
Adding $psake.error_message per #119
#119
Added $psake.error_messge pester check to current tests.
> (GH119) add $psake.error_message

- src/public/Invoke-Task.ps1
This is the pull request to go along with #258
The task durations in the Build Time Report are cumulative instead of specific to each task.
For the following psake script:
```
properties {  
}
task default -depends Three
task Three -depends One, Two {
write-host "Sleeping 1"
Sleep 1
}
task Two -depends One {
write-host "Sleeping 2"
Sleep 2
}
task One {
write-host "Sleeping 1"
Sleep 1
}
```
I would expect the output to be:
```
----------------------------------------------------------------------
Build Time Report
----------------------------------------------------------------------
Name   Duration
----   --------
One    00:00:01.003
Two    00:00:02.003
Three  00:00:01.003
Total: 00:00:04.020
```
But the output is:
```
---------------------------------------------------------------------- …
```
> (GH258) Change duration to be per task instead of cumulative

- docs/how-to-fail-a-build.md
This fixes the documentation issue in #169
Updates the /docs/how-to-fail-a-build.md
#169 
simple change, open issue, fix identified in the original issue
no testing done
n/a
documentation change only
not applicable
> fix #169 how-to-fail-a-build docs

- src/public/Exec.ps1
Use $global:lastexitcode as described in https://github.com/psake/psake/issues/203.
https://github.com/psake/psake/issues/203
Check https://github.com/psake/psake/issues/203
> Use $global:lastexitcode instead of $lastexitcode in Exec

- .gitattributes
- src/psake
- src/psake.cmd
- src/psake.ps1
There is `psake.cmd` wrapper script to run psake tasks on Windows. I added a similar wrapper for Linux and macOS.
- Set correct exit code in psake.ps1.
- Introduce psake wrapper script.
- Make src/psake executable, set correct autocrlf settings.
#262
It allows to use `psake` command to run psake tasks on Linux and macOS. Also psake.ps1 returns correct exit code now.
I created tasks that may produce errors:
```powershell
Task test `
{
Hi-There
}
```
```sh
echo 'Task test { Hi-There }' > Test1.ps1
```
```powershell
Task test `
-requiredVariables @('SomeValue') `
{
"Test $SomeValue"
}
```
```sh
echo "Task test -requiredVariables @('SomeValue') { \"Test \$SomeValue\" }" > Test2.ps1
```
```powershell
Task test `
{
$PSVersionTable
}
```
```sh
echo 'Task test { $PSVersionTable }' > Test3.ps1
``` …
> Add wrapper script for Linux and macOS

- src/public/Invoke-psake.ps1
Add `try/catch` block around parameters initialization loop. In `catch` show `$parameters.$keys`, and then throw an error.
https://github.com/psake/psake/issues/271
You can have a bunch of parameters, which must be initialized by a build server and passed to Invoke-psake. If one of them is not passed, you get:
` +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Cannot process argument because the value of argument "value" is null. Change the value of argument "value" to a non
-null value.`
And it's really not clear which parameter is null.
Manually.
> Extend parameters initialization error handling. If parameters initialization failed, show which parameter caused a failure.

- specs/taskTearDown_runs_on_failed_test_has_access_to_error_and_should_fail.ps1
- specs/taskTearDown_runs_on_success_should_pass.ps1
- specs/tasksetup_with_task_argument_should_pass.ps1
- src/private/FormatErrorMessage.ps1
- src/public/Invoke-Task.ps1
- src/public/Invoke-psake.ps1
- src/public/Task.ps1
- src/public/TaskSetup.ps1
- src/public/TaskTearDown.ps1
I have copied the exception handling from `Invoke-Psake` into the try/catch block of `Invoke-Task` so that we can trap errors and capture error detail before invoking the `finally` clause which calls `TaskTearDown`; this allows `TaskTearDown` to operate in the context of the current task's status including any error detail on failure.
This PR also proposes passing the `$task` parameter in the heart of `Invoke-Task` into `TaskSetup` and `TaskTearDown` as optional parameters so that instead of doing this:
```
taskSetup {
"Begin task: '$($psake.context.Peek().currentTaskName)'"
}
```
we can do this:
```
taskSetup {
"Begin task: '$($psake.context.Peek().currentTaskName)'"
}
```
Using the same technique in `TaskTearDown` and setting some additional properties on the `Task` instance we can now …
> Pass task detail including error into TaskSetup and TaskTearDown

- specs/dotNet4.8_should_pass.ps1
- src/private/ConfigureBuildEnvironment.ps1
Added .net 4.8 to ConfigureBuildEnvironment.ps1, with only build tools 15.0
#280 
ci/cd tests are passing
> Add support .net 4.8

- CHANGELOG.md
- src/private/ConfigureBuildEnvironment.ps1
- src/psake.psd1
Fix issues described in #278, where the path for 15.0 tools is determined when only 16.0 tools are installed.
The logic in ConfigureBuildEnvironment which determines $frameworkDirs was incorrectly including 16.0 (e.g. VS 2019) in it's version lookup. If 16.0+ of VSSetupInstance existed, the $frameworkDir would incorrectly be set to MSBuild\15.0\Bin\amd64.
Change the logic to constrain version search to [15.0, 16.0) for $buildToolsVersions containing "15.0", and allowing [16.0, ] to be considered for "16.0"
Also, include MSBuild 16.0 in the 4.8 environment configuration path.
#278 
Allows building when only VS 2019 (or tools) are installed.
Executed .\build.ps1 Build && .\build.ps1 Test
Locally on two machines - 
1 containing VS 2019 Professional only, 
1 containing VS 2017 build tools …
> Fix for path issue for VS 2019 described in comments of #278

- docs/reference/functions/BuildSetup.md
- docs/reference/functions/BuildTearDown.md
- docs/structure-of-a-psake-build-script.md
- specs/buildsetup_can_access_properties_should_pass.ps1
- specs/buildsetup_failure_should_fail.ps1
- specs/buildsetup_runs_once_should_pass.ps1
- specs/buildteardown_can_access_properties_should_pass.ps1
- specs/buildteardown_failure_should_fail.ps1
- specs/buildteardown_runs_once_should_pass.ps1
- src/private/ExecuteInBuildFileScope.ps1
- src/public/BuildSetup.ps1
- src/public/BuildTearDown.ps1
- src/public/Invoke-psake.ps1
Similar to TaskSetup and TaskTearDown, there are now functions to specify code snippets to be executed at the beginning of the build (before the first task), and at the end of the build (after either all tasks have completed, or a task has failed).
This is my first ever contribution to an opensource project, and first time using GitHub, so go easy on me :)
https://github.com/psake/psake/issues/181
In my implementation of psake, I need to perform some processing at the very beginning of the build, before any tasks run.
Previously, I had just worked around this using the TaskSetup functionality, and a variable to track whether the build setup had been performed. This approach isn't compatible with a change which I now want to make to our builds, which requires the build setup to have been …
> BuildSetup and BuildTearDown Feature

- specs/exec_executes_in_specified_location_should_pass.ps1
- src/public/Exec.ps1
In case of command failure retry running command on he location passed by caller
Lets say caller wan't to Exec deletion of all files inside D:\ folder and retry it max 10 times.
We are running script in E:\ folder
Old/current code would have changed location to E:\ (correctly), try and fail on deleting all files and will pop location back to E:\
Next 9 attempts will run inside E:\
Now we will push and pop on each attempt
Mistake was in #200 
Mentioned in description
Because this is an easy fix I just tested in small sample build script
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [ x] All new and existing tests passed.
> In case of failure rerun command in specified location

- specs/invoketask_with_continueonerror_should_pass.ps1
- src/public/Invoke-Task.ps1
1. Created a Pester test to assert that the -ContinueOnError parameter has the desired behaviour.
2. Removed the additional call stack pop from Invoke-Task, which was causing that test to fail.
3. Added a try...finally to Invoke-Task immediately after the task is pushed onto the stack. The finally block ensures that the task is always popped, even if the task fails. This resolved a new bug which surfaced, where if a task with -ContinueOnError depends on another task, which fails, the failed task would not pop itself from the stack, and when the dependent task tried to pop itself from the stack, it would actually pop the failed task, causing a validation error.
#295
As described in the issue, this is an issue which has broken a feature which previously worked.
Created a new Pester test, …
> Fix continueonerror

- src/public/Exec.ps1
to enable more compact build tasks
adding the alias "wd" for the "workingDirectory" parameter of the Exec command.
It helps putting short commands in a single line and still keep them readable.
Especially usefull when putting many tasks below each other in a tabular form
The change is minimal intrusive, and using a default Powershell feature. Not adding any testable logic.
> provide a shorter alias for workingDirectory

- docs/where-can-i-get-psake.md
This PR modifies doc. It adds a new line after paragraph to help MKDocs understand the following lines form a list.
It fixes a formatting issue on the page https://psake.readthedocs.io/en/latest/where-can-i-get-psake/. Without newline, MKDocs doesn't understand Markdown.
Before my changes:
After:
> (doc) Fix formatting in "Where can I get psake"

- src/public/Get-PSakeScriptTasks.ps1
#308 
```
ps>Get-Help Get-PSakeScriptTasks -Full
NAME
Get-PSakeScriptTasks
SYNOPSIS
Returns meta data about all the tasks defined in the provided psake script.
SYNTAX
Get-PSakeScriptTasks [[-BuildFile] <String>] [<CommonParameters>]
DESCRIPTION
Returns meta data about all the tasks defined in the provided psake script.
PARAMETERS
-BuildFile <String>
The path to the psake build script to read the tasks from.
Required?                    false
Default value
<CommonParameters>
This cmdlet supports the common parameters: Verbose, Debug,
ErrorAction, ErrorVariable, WarningAction, WarningVariable,
OutBuffer, …
```
> Refactor: Get-PSakeScriptTasks

- src/public/Framework.ps1
#308 
```
ps>Get-Help Framework -Full
NAME
Framework
SYNOPSIS
Sets the version of the .NET framework you want to use during build.
SYNTAX
Framework [-Framework] <String> [<CommonParameters>]
DESCRIPTION
This function will accept a string containing version of the .NET framework to use
during build.
Possible values: '1.0', '1.1', '2.0', '2.0x86', '2.0x64', '3.0', '3.0x86', '3.0x64',
'3.5', '3.5x86', '3.5x64', '4.0', '4.0x86', '4.0x64', '4.5', '4.5x86', '4.5x64',
'4.5.1', '4.5.1x86', '4.5.1x64'.
Default is '3.5*', where x86 or x64 will be detected based on the bitness of the
PowerShell process.
PARAMETERS
-Framework <String>
Version of the .NET framework to use during build.
Position? …
```
> Refactor: Framework

- src/public/Exec.ps1
#308 
```
ps>Get-Help Exec -Full
NAME
Exec
SYNOPSIS
Helper function for executing command-line programs.
SYNTAX
Exec [-Cmd] <ScriptBlock> [[-ErrorMessage] <String>] [[-MaxRetries] <Int32>]
[[-RetryTriggerErrorPattern] <String>] [[-WorkingDirectory] <String>]
[<CommonParameters>]
DESCRIPTION
This is a helper function that runs a scriptblock and checks the PS variable
$lastexitcode to see if an error occcured.
If an error is detected then an exception is thrown.
This function allows you to run command-line programs without having to explicitly
check fthe $lastexitcode variable.
PARAMETERS
-Cmd <ScriptBlock>
The scriptblock to execute. This scriptblock will typically contain the
command-line invocation.
Required? …
```
> Refactor: Exec

- src/public/BuildTearDown.ps1
#308 
```
ps>Get-Help BuildTearDown -Full
NAME
BuildTearDown
SYNOPSIS
Adds a scriptblock that will be executed once at the end of the build
SYNTAX
BuildTearDown [-Setup] <ScriptBlock> [<CommonParameters>]
DESCRIPTION
This function will accept a scriptblock that will be executed once at the end of the
build, regardless of success or failure
PARAMETERS
-Setup <ScriptBlock>
A scriptblock to execute
Default value
<CommonParameters>
This cmdlet supports the common parameters: Verbose, Debug,
ErrorAction, ErrorVariable, WarningAction, WarningVariable,
OutBuffer, PipelineVariable, and …
```
> Refactor: BuildTearDown

- src/public/Assert.ps1
#308 
```
ps>Get-Help Assert -Full
NAME
Assert
SYNOPSIS
Helper function for "Design by Contract" assertion checking.
SYNTAX
Assert [-ConditionToCheck] <Object> [-FailureMessage] <String> [<CommonParameters>]
DESCRIPTION
This is a helper function that makes the code less noisy by eliminating many of the
"if" statements that are normally required to verify assumptions in the code.
PARAMETERS
-ConditionToCheck <Object>
The boolean condition to evaluate
Default value
-FailureMessage <String>
The error message used for the exception if the ConditionToCheck parameter is
false
Required? …
```
> Refactor: Assert

- src/public/TaskTearDown.ps1
#308 
```
ps>Get-Help TaskTearDown -Full
NAME
TaskTearDown
SYNOPSIS
Adds a scriptblock to the build that will be executed after each task
SYNTAX
TaskTearDown [-TearDown] <ScriptBlock> [<CommonParameters>]
DESCRIPTION
This function will accept a scriptblock that will be executed after each task in the
build script.
The scriptblock accepts an optional parameter which describes the Task being torn
down.
PARAMETERS
-TearDown <ScriptBlock>
A scriptblock to execute
Default value
<CommonParameters>
This cmdlet supports the common parameters: Verbose, Debug,
ErrorAction, ErrorVariable, …
```
> Refactor: TaskTearDown

- src/public/TaskSetup.ps1
#308 
```
ps>Get-Help TaskSetup -Full
NAME
TaskSetup
SYNOPSIS
Adds a scriptblock that will be executed before each task
SYNTAX
TaskSetup [-Setup] <ScriptBlock> [<CommonParameters>]
DESCRIPTION
This function will accept a scriptblock that will be executed before each task in
the build script.
The scriptblock accepts an optional parameter which describes the Task being setup.
PARAMETERS
-Setup <ScriptBlock>
A scriptblock to execute
Default value
<CommonParameters>
This cmdlet supports the common parameters: Verbose, Debug,
ErrorAction, ErrorVariable, WarningAction, WarningVariable, …
```
> Refactor: Tasksetup

- .github/workflows/CI.yml
- requirements.psd1
- tests/Help.tests.ps1
Pester is pre-installed on Windows GitHub runner and is using a newer version. This should fix the tests.
The Windows GitHub tests fail because a newer version is required.
Will be tested via CI
> Fix CI Testing

- src/private/ConfigureBuildEnvironment.ps1
Adds MS Build 17 support (included with Visual Studio 2022).
Fixes #312 
We have MS Build 16 and 17 installed on multiple TeamCity build agents, but the behavior of selecting the used version is not identical on all agents. Some of them select MS Build 17 as desired, while others select version 16, which lacks support for newer C# language versions, for example.
Tested on TeamCity build agents of the company I'm consulting for.
Builds now succeed on agents that were failing before.
Note: Selecting MS Build 17 could perhaps arguably be considered a breaking change. In some edge cases our project files required some adjustments to make them build. However, the fact that the user installed the new version probably means they want to use it.
> Support MS Build 17 (Visual Studio 2022)

- docs/README.md
Happened to notice this when reviewing docs associated with the latest release of psake.
> (doc) Fix minor typo

- .github/workflows/CI.yml
This changes the CI workflow to only run when files under the src directory change.
> Run CI only when src changes

- .markdownlint.json
- .vscode/settings.json
- CHANGELOG.md
- docs/customising-logging.md
- psakeFile.ps1
- specs/outputHandler_routes_messages_to_specified_handler_type_should_pass.ps1
- specs/outputhandler_routes_messages_to_specified_handler_type/outputhandler_routes_messages_to_specified_handler_type.ps1
- specs/outputhandler_routes_messages_to_specified_handler_type/psake-config.ps1
- specs/outputhandler_routes_unknown_message_type_to_default_handler/outputhandler_routes_unknown_message_type_to_default_handler.ps1
- specs/outputhandler_routes_unknown_message_type_to_default_handler/psake-config.ps1
- specs/outputhandler_routes_unknown_message_type_to_default_handler_should_pass.ps1
- specs/use_writeoutput_function_throughout/psake-config.ps1
- specs/use_writeoutput_function_throughout/use_writeoutput_function_throughout.ps1
- specs/use_writeoutput_function_throughout_should_pass.ps1
- src/private/ConfigureBuildEnvironment.ps1
- src/private/CreateConfigurationForNewContext.ps1
- src/private/ExecuteInBuildFileScope.ps1
- src/private/WriteDocumentation.ps1
- src/private/WriteOutput.ps1
- src/private/WriteTaskTimeSummary.ps1
- src/psake-config.ps1
- src/psake.psm1
- src/public/Invoke-Task.ps1
- src/public/Invoke-psake.ps1
- src/public/Task.ps1
There is a new WriteOutput function, which is used throughout the psake code whenever messages need to be logged. The function simply passes the message and message type to an "outputHandler" script block, which can be overridden in psake-config. So you can override exactly how output is handled by overriding that outputHandler script block.
The default outputHandler script block further routes the output according to it's output type (warning, verbose, error, etc) to corresponding script blocks which can also be overridden by psake-config. So you also have the option of overriding how a single type of output is handled.
The default outputHandlers for each message type outputs the message exactly as it would have been prior to this new feature, so it is a non-breaking change.
#65 
As …
> Ability to override how psake's internal logging is handled

- CHANGELOG.md
- specs/include_can_process_fileinfo_from_pipeline_should_pass.ps1
- specs/include_can_process_strings_from_pipeline_should_pass.ps1
- src/public/Include.ps1
You can now do this : 
```
$("File1.ps1","File2.ps1") | Include
Get-ChildItem | Include
```
#289 
Allows users to write slightly more concise code, rather than writing for loops.
New Pester tests have been added to verify that it can accept pipeline input both in the form of strings and FileInfo objects.
I also manually tested that it was backwards compatible, and could still work with the fileNamePathToInclude parameter.
> Enabling String and FileInfo Objects To Be Piped To Include Function
